### ISSUE TITLE
Add option to create clusters from Manager

### ISSUE THREAD

**Issue by AlexGodbehere** [AMRC-FactoryPlus/acs-manager#71]
Administrators should be able to create `EdgeClusterConfiguration` entries in the ConfigDB when a new cluster is required. It has a simple structure, with `name` and `namespace` keys. The `flux` entry is automatically created by the ECO.

When creating the General Object Information entry it would be useful to include location data.

Having a list of existing clusters would also be useful. Deleting the clusters is not a required feature at this stage.

**Comment by AlexGodbehere** [comment]
Added the relevant entries to the auth dumps but still getting a `403` on `$uuid = $configDB->createObject(Klass::EdgeCluster, name: $name)['uuid'];`

**Comment by amrc-benmorrow** [comment]
Once a cluster has been created, POST to the EDO URL `/v1/cluster/:uuid/bootstrap-url`. This will return 404 until the cluster has been set up in the central services. After that it will return a JSON string holding an external, public URL which can be used to fetch a bootstrap script for this cluster.

The reason for the extra indirection (rather than a fixed bootstrap script URL) is that I want to keep the option open of generating a URL with a secure token in rather than just allowing public access. This is a POST URL because it might be generating a new token.
